blank_issues_enabled: true
contact_links:
  - name: Issue
    about: Issue template
    url: https://github.com/Ayato-kosaka/spelieve/issues/new?template=issue.md&projects=Ayato-kosaka/1&labels=enhancement
