name: EAS Build Develop
on:
  push:
    branches:
      - develop
    paths:
      - 'app.config.ts'
  workflow_dispatch:
    inputs:
      expo-cache:
        type: choice
        description: 'Whether to use Expo cache'
        default: true
        required: false
        options:
          - "true"
          - "false"

jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: 4.x
          token: ${{ secrets.EXPO_TOKEN }}
          expo-cache: ${{ github.event.inputs.expo-cache }}

      - name: Checkout spelieve-secret
        uses: actions/checkout@v3
        with:
          repository: Ayato-kosaka/spelieve-secret
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          path: spelieve-secret

      - run: 'mv ./spelieve-secret/spelieve-frontend/release/ENV.ts ./src'
      - run: 'mv ./spelieve-secret/spelieve-frontend/release/GoogleService-Info.plist ./'
      - run: 'mv ./spelieve-secret/spelieve-frontend/release/google-services.json ./'

      - run: 'rm -rf spelieve-secret/'

      - name: Install dependencies
        run: npm ci

      - name: Build on EAS
        run: npx eas-cli build --profile development --platform all --non-interactive --no-wait
