name: Firebase Hosting Preview
on:
  push:
    branches:
      - develop
  workflow_dispatch:
    inputs:
      target:
        type: choice
        description: Deploy environment
        options:
          - production
          - release
          - development
        required: true
env:
  TARGET: ${{ github.event.inputs.target || 'release' }}
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout spelieve-secret
        uses: actions/checkout@v3
        with:
          repository: Ayato-kosaka/spelieve-secret
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          path: spelieve-secret
      - run: 'mv ./spelieve-secret/spelieve-frontend/${{ env.TARGET }}/ENV.ts ./src'
      - run: 'rm -rf spelieve-secret/'
      - run: 'npm ci && npm i -g expo-cli && expo build:web'
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ITINERARY_4AEE3 }}'
          projectId: itinerary-4aee3
          channelID: ${{ env.TARGET }}
